# Generated by Django 2.1.5 on 2019-08-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20180419_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='owner',
            new_name='user',
        ),
    ]
